const STATUS_USUARIO = {
  ATIVO: 'ATIVO',
  INATIVO: 'INATIVO',
  DESLIGADO: 'DESLIGADO',
  FERIAS: 'FERIAS',
  AFASTAMENTO: 'AFASTAMENTO',
  REATIVADO: 'REATIVADO',
};

const STATUS_AUTENTICAVEIS = [
  STATUS_USUARIO.ATIVO,
  STATUS_USUARIO.REATIVADO,
];

const STATUS_BLOQUEADOS = [
  STATUS_USUARIO.INATIVO,
  STATUS_USUARIO.DESLIGADO,
  STATUS_USUARIO.FERIAS,
  STATUS_USUARIO.AFASTAMENTO,
];

module.exports = {
  STATUS_USUARIO,
  STATUS_AUTENTICAVEIS,
  STATUS_BLOQUEADOS,
};